// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4g2l7ODFLIuRloDrHlMA0IDbYfV4LWTI',
    appId: '1:313134687433:web:f0c31cff77d6a6b27a5918',
    messagingSenderId: '313134687433',
    projectId: 'nullnull-flutter',
    authDomain: 'nullnull-flutter.firebaseapp.com',
    storageBucket: 'nullnull-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwq3cBK9_hbYkti3DfZzErnUkH9J8ZA5k',
    appId: '1:313134687433:android:8796761c0ff020467a5918',
    messagingSenderId: '313134687433',
    projectId: 'nullnull-flutter',
    storageBucket: 'nullnull-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCHYGjzi0n30C9VY18aq85r60id1brCkU',
    appId: '1:313134687433:ios:c6ffd8596048563b7a5918',
    messagingSenderId: '313134687433',
    projectId: 'nullnull-flutter',
    storageBucket: 'nullnull-flutter.firebasestorage.app',
    iosBundleId: 'kr.co.nullnull',
  );
}
